pipeline {
    agent any
    environment {
        PYTHON_HOME = 'C:/Python312'
        PATH = "${env.PYTHON_HOME}/Scripts;${env.PATH}"
        PYTHONPATH = "${env.WORKSPACE}/test_automation"
    }
    stages {
        stage('Cleaning up the Jenkins directory') {
            steps {
                script {
                    bat """
                    del /F /Q PlayWright_SL
                    """
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    bat """
                    ${env.PYTHON_HOME}/python -m venv venv
                    call venv\\Scripts\\activate
                    pip install --upgrade pip
                    pip install -r test_automation/requirements.txt
                    playwright install"
                    """
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    bat """
                    call venv\\Scripts\\activate
                    pytest
                    """
                }
            }
        }
    }
    post {
            always {
                script {
                    bat """
                    call venv\\Scripts\\activate
                    allure generate allure-results --clean -o allure-report
                    """
                }
            }
        }
}
